version: "3"
services:
  app:
    build: .
    ports:
      - 8081:8081
    environment:
      - NEURALYZER_SERVER_PORT
      - NEURALYZER_SERVER_HOSTNAME
      - NEURALYZER_FLAT_BUFFERS_ENABLED
      - NEURALYZER_TICK_RATE
      - NEURALYZER_SSL_ENABLED
      - NEURALYZER_SSL_CERT
      - NEURALYZER_SSL_KEY
      - NEURALYZER_SSL_CA
      - NEURALYZER_NODE_ENV
      - NEURALYZER_REDIS_HOST
      - NEURALYZER_REDIS_PORT
      - NEURALYZER_REDIS_PASSWORD
      - NEURALYZER_CONSOLE_LOG_LEVEL
      - NEURALYZER_S3_LOGGER_ENABLED
      - NEURALYZER_S3_ACCESS_KEY_ID
      - NEURALYZER_S3_SECRET_ACCESS_KEY
      - NEURALYZER_S3_LOG_BUCKET
      - NEURALYZER_S3_LOG_DURATION
      - NEURALYZER_S3_LOG_LEVEL
      - NEURALYZER_S3_LOG_FILENAME
    restart: on-failure
